include: package:flutter_lints/flutter.yaml

analyzer:

linter:
  rules:
    avoid_print: true
    require_trailing_commas: true
    prefer_single_quotes: true
    cascade_invocations: true
    always_use_package_imports: true
    prefer_final_in_for_each: true
    avoid_redundant_argument_values: true
    unnecessary_string_interpolations: true
    # always_specify_types: true
