version: 2.1
aliases:
  - &restore-cache
    restore_cache:
        keys:
        - v1-dependencies-
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - &install-deps
    run:
        name: Install dependencies
        command: npm i

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    environment:
      DOCKER_IMAGE: ichhoa129/discord-bot
      DOCKER_TAG: latest
    working_directory: ~/smartfood.cooking/services/app-service
    docker:
      - image: circleci/node:14
      - image: docker:17.09.1-ce-git  
    steps:
      - checkout
      - setup_remote_docker
      - *restore-cache
      - run: npm cache clear --force
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - *install-deps
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  deploy:
    machine:
      enabled: true
    working_directory: ~/smartfood.cooking/services/app-service
    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:b8:cc:b7:ee:43:48:ed:2f:59:5d:9e:99:a9:89:c0"
      - run: 
          name: Deploy via ssh
          command: |
              echo Starting to deploy server
              ssh -v $SSH_USER@$SSH_HOST 'cd ~/smartfood.cooking/services/app-service && git checkout dev-v1.0 && git pull && chmod 777 ./script/deploy.sh && ./script/deploy.sh'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - dev-v1.0
